date.timezone = "Asia/Tokyo"

[mbstring]
default_charset = "UTF-8"
mbstring.language = "Japanese"

; 1ファイルあたりの最大アップロードサイズ
upload_max_filesize = 2M

; 1回のリクエストの最大サイズ
post_max_size = 8M

; スクリプトが消費できる最大メモリ
memory_limit = 128M